#ifndef ADHOC_ROUTING_CONSTANTS
#define ADHOC_ROUTING_CONSTANTS

/* routing packet*/
#define SEQUENCE_NO_SIZE 4
#define TYPE_SIZE 1
#define PACKET_LENGTH_SIZE 4
#define ADDR_SIZE 4

#define INDEX_SEQUENCE_NO 0
#define INDEX_TYPE INDEX_SEQUENCE_NO+SEQUENCE_NO_SIZE
#define INDEX_PACKET_LENGTH INDEX_TYPE+TYPE_SIZE
#define INDEX_SRC INDEX_PACKET_LENGTH+PACKET_LENGTH_SIZE
#define INDEX_DEST INDEX_SRC+ADDR_SIZE

/* packet type */
#define RREQ 1
#define RREP 2
#define RERR 3
#define DATA 4

/* fragmentation */
#define SEQUENCE_NUMBER_SIZE 4
#define FRAGMENT_ID_SIZE 1
#define NUM_OF_FRAGMENTS_SIZE 1
#define TOTAL_LENGTH_SIZE 4
#define REMOTE_ADDRESS_SIZE ADDR_SIZE

#define FRAGMENT_LENGTH_SIZE 4

#define INDEX_SEQUENCE_NUMBER 0
#define INDEX_FRAGMENT_ID INDEX_SEQUENCE_NUMBER+SEQUENCE_NUMBER_SIZE
#define INDEX_NUM_OF_FRAGMENTS INDEX_FRAGMENT_ID+FRAGMENT_ID_SIZE
#define INDEX_TOTAL_LENGTH INDEX_NUM_OF_FRAGMENTS+NUM_OF_FRAGMENTS_SIZE
#define INDEX_REMOTE_ADDRESS INDEX_TOTAL_LENGTH+TOTAL_LENGTH_SIZE

#define INDEX_FRAGMENT_LENGTH INDEX_REMOTE_ADDRESS+REMOTE_ADDRESS_SIZE
#define INDEX_PAYLOAD INDEX_FRAGMENT_LENGTH+FRAGMENT_LENGTH_SIZE

#define ARF_HEADER_LENGTH SEQUENCE_NUMBER_SIZE+FRAGMENT_ID_SIZE+NUM_OF_FRAGMENTS_SIZE+TOTAL_LENGTH_SIZE+REMOTE_ADDRESS_SIZE
#endif